---
title: "P50_correlation_mediation"
author: "Xue Zhang"
date: "8/31/2022"
output: html_document
---

### load envionment and packages and subfunctions
```{r setup, include=FALSE}
# use here from the here package
here <- here::here

# set up environment and load useful packages
source(here('R', 'set_up_env.R'))

# load functions for data manipulations
source(here('R', 'data_manipulation.R'))

# load functions for data visualization, including tables and figures
source(here('R', 'visualization.R'))

# load functions for folder manipulation
source(here('R','folder_manipulation.R'))
```

### define data dir and create folders for output figures
```{r define_folders}
# data folder
csvdir = "/Users/xuezhang/Documents/Stanford/Projects/P50/Analysis/CSV"

# define and create figure folder
Figuredir = here("Figures")
Figsubdir = c("TIFF","PDF")
Figsubsubdir = c("Boxplot", "RepeatedCorrelation")
for (subdir in Figsubdir) {
  for (subsubdir in Figsubsubdir) {
    des_dir <- paste0(Figuredir, "/", subdir, "/", subsubdir)
    create_folder_subfolder(des_dir)
  }
}

```


```{r define_parameters}
# subjects
subjn = 14 # sub num + 1
subj_list = as.character(1:(subjn-1))
subj_label = c(1:(subjn-1))

# dosage information
dosage_level <- c("Placebo", "0.05mg/kg", "0.5mg/kg")
dosage_level_2ses <- c("Placebo", "0.5mg/kg")
Dosage <- import(paste(csvdir,"/Ket_Dose_unblinded_demo.xlsx",sep = ""))

# for plot
xlabels_2time = c("Pre", "Post")
face_label = c(`Placebo` = "i. Placebo",
               `0.05mg/kg` = "ii. 0.05mg/kg",
               `0.5mg/kg` = "iii. 0.5mg/kg"
               )

# figure related parameters
mycolor <- colorRampPalette(brewer.pal(name="Set1", n = 9))(length(subj_label))

xtitle_size = 4
title_size = 7
legend_title_size = 9
xlabel_size = 7

```

# read questionnaire data (CADSS and 5D-ASC) and FEET activation data from amygdala and anterior insula
```{r read data}
source(here('R', 'read_redcap_data.R'))
source(here('R', 'read_fmri_data.R'))
```

# mediation models
```{r}
options(contrasts = c("contr.sum","contr.poly"))
# combine all CADSS and 5D-ASC subcomponents of all three visits
non_brain_data_post_pre <- Reduce(function(x, y) merge(x, y, by = c("Subjects", "Dosage"), all=TRUE), list(data_repeated_post_pre, data_once_pervisit))
### combine non-neuroimaging and neuroimaging data
# Faces: nonconscious Threat vs. Neutral
Faces_data_contrast <- Faces_data %>%
  filter(Contrast == "ThreatvsNeutral" & Task == "nonconscious") %>%
  select(-Task, -Contrast)

original_cols <- colnames(Faces_data_contrast)[-1:-2]
colnames(Faces_data_contrast)[-1:-2] <- paste("noncon_TvN", original_cols,sep="_")

all_data <- Reduce(function(x, y) merge(x, y, by = c("Subjects", "Dosage"), all=TRUE), list(non_brain_data_post_pre, Faces_data_contrast)) %>%
  filter(!(Dosage %in% c('0.05mg/kg', 'Baseline')))

all_data_forcorr <- all_data %>%
  select(Subjects, Dosage, CADSS_depersonalization_post_pre, CADSS_derealization_post_pre, dascscore_bliss, CADSS_amnesia_post_pre, dascscore_anxiety, matches('Insula'))

stat.test_cohen <- all_data_forcorr %>%
  pivot_longer(-c(Subjects, Dosage), names_to = "variables", values_to = "value") %>%
  group_by(variables) %>%
  cohens_d(value ~ Dosage, paired = TRUE) %>%
  kbl(caption = "Cohen's d") %>%
  kable_classic(full_width = F, html_font = "Arial", font_size = 10)
    
## calculate intra-subject correlation between insula activation and CADSS and 5D-ASC
rmc_variables <- colnames(all_data_forcorr)[-1:-2]
plot_variable <- c('Depersonalization','Derealization', 'Bliss', 'Amnesia', 'Anxiety', 'Insula activation')
r_rmc <- matrix(data = 0, nrow = length(rmc_variables), ncol = length(rmc_variables))
p_rmc <- matrix(data = 1, nrow = length(rmc_variables), ncol = length(rmc_variables))
for (ivar in 1:length(rmc_variables)) {
  for (jvar in 1:length(rmc_variables)) {
  rmc <- rmcorr(Subjects, rmc_variables[ivar],rmc_variables[jvar],all_data_forcorr)
    p_rmc[ivar, jvar] <- rmc$p
    r_rmc[ivar, jvar] <- rmc$r
  }
}
# conduct multiple comparsion correction for intra-subject correlation
p_rmc_plot <- p_rmc
r_rmc_plot <- r_rmc
p_rmc_plot_vec <- as.vector(p_rmc_plot[upper.tri(p_rmc_plot)])
p_rmc_plot_vec_adj <- p.adjust(p_rmc_plot_vec, method = "fdr")
p_rmc_plot_adj <- matrix(1, nrow = dim(p_rmc_plot)[1], ncol = dim(p_rmc_plot)[2])
p_rmc_plot_adj[upper.tri(p_rmc_plot)] <- p_rmc_plot_vec_adj
p_rmc_plot_adj[lower.tri(p_rmc_plot)] <- p_rmc_plot[lower.tri(p_rmc_plot)]

colnames(r_rmc_plot) <- plot_variable
rownames(r_rmc_plot) <- plot_variable
colnames(p_rmc_plot) <- plot_variable
rownames(p_rmc_plot) <- plot_variable
colnames(p_rmc_plot_adj) <- plot_variable
rownames(p_rmc_plot_adj) <- plot_variable

col<- colorRampPalette(c("blue", "white","red"))(8)
tiff(file=paste(Figuredir, "/TIFF/RepeatedCorrelation/rmcorr_insula", sep = ""), width=5, height=5, res=300, units="in")
corrplot(r_rmc_plot, method = "number", tl.col="black", tl.srt=45, p.mat = p_rmc_plot_adj, sig.level = 0.05, insig = "blank", col = col)
dev.off()

pdf(file=paste(Figuredir, "/PDF/RepeatedCorrelation/rmcorr_insula", sep = ""), width=3.7, height=3.7)
corrplot(r_rmc_plot, tl.col="black", tl.srt=90, p.mat = p_rmc_plot_adj, sig.level = 0.05,number.digits = 2, insig = "blank", col = col)
dev.off()



# mediators
mediators <- colnames(all_data)[4:9]
dvs <- colnames(all_data)[c(11)] # insula activation
df_total = data.frame()
detach("package:lmerTest", unload=TRUE)
library(mediation)
for (imed in 1: length(mediators)) {
  mediator <- mediators[imed]
  for (idv in 1:length(dvs)) {
    dv <- dvs[idv]
    
    
    test_data <- all_data %>%
      select(c('Subjects', 'Dosage', dv, mediator)) %>%
      na.omit() 
    
    b <- test_data %>%
      ggplot(aes_string(x = dv, y = mediator)) + geom_point(aes(color = Dosage),size = 1, alpha=1)

    # z score across all conditions
    test_data <- test_data %>%
      mutate_at(colnames(test_data)[3:4], ~(scale(as.numeric(.), center = TRUE, scale = TRUE) %>% as.vector))
        
    # within subject demean
    test_data <- test_data %>%
      group_by(Subjects) %>%
      mutate_at(colnames(test_data)[3:4], ~(scale(as.numeric(.), center = TRUE, scale = FALSE) %>% as.vector))
    
    # iv -> dv
    formula_totaleffect <- as.formula(paste(dv, " ~ Dosage + (1|Subjects)"))
    model_totaleffect <- lmer(formula_totaleffect, data = test_data, REML = FALSE)
    anova(model_totaleffect,type = 'marginal')
    
    # iv -> mediator
    formula_mediator <- as.formula(paste(mediator, " ~ Dosage + (1|Subjects)"))
    model_mediator <- lmer(formula_mediator, data = test_data, REML = FALSE)
    anova(model_mediator,type = 'marginal')
    
    # {iv, mediator} -> dv
    formula_dv <- as.formula(paste(dv, " ~ " , mediator, " + Dosage + (1|Subjects)"))
    model_dv <- lmer(formula_dv, data = test_data, REML = FALSE)
    anova(model_dv,type = 'marginal')
    
    # mediation model
    mediatorModel <- mediate(model_mediator, model_dv, treat='Dosage', control.value = "Placebo", treat.value = "0.5mg/kg", mediator=mediator)
    a <- summary(mediatorModel) 
    
    if (a$d0.p < 1) { # was 0.05 for the paper
      print(paste(mediator, ' ', dv, ' ', a$d0, ' ', a$d0.ci[1], ' ', a$d0.ci[2], ' ', a$d0.p))
      model <- cbind(mediator, dv, a$d0, a$d0.ci[1], a$d0.ci[2], a$d0.p, a$z0, a$tau.coef, fixef(model_mediator)[2], fixef(model_dv)[2])
      df_total <- rbind(df_total,model)
 
    }
 
  }
  
}
if (length(df_total) > 0) {
      colnames(df_total) <- c('mediator', 'dependent variable', 'ACME', 'upper CI', 'lower CI','p','direct','total','iv-med','med-dv')
    }

```

# visualization of high dissociator vs. low dissociator
```{r}
# visualization for 0.5 and placebo individually
all_data <- Reduce(function(x, y) merge(x, y, by = c("Subjects", "Dosage"), all=TRUE), list(non_brain_data_post_pre, Faces_data_contrast)) %>%
  filter(Dosage != '0.05mg/kg')

# mediators
mediators <- colnames(all_data)[c(4:9)]
# dependent variable
dvs <- colnames(all_data)[c(10)]


imed = 1 # change to visualize different mediator
mediator <- mediators[imed]
idv = 1
dv <- dvs[idv]

test_data <- all_data %>%
  select(c('Subjects', 'Dosage', dv, mediator)) %>%
  na.omit() 

# get values for high and low dissociators
highdose <- test_data$Dosage == "0.5mg/kg"
subject_highdose <- test_data$Subjects[highdose]
cadss_highdose <- test_data %>%
  filter(highdose) %>%
  select(mediator)

disso_median <- cadss_highdose %>%
  summarise(median = median(get(mediator), na.rm = TRUE))

disso_median <- disso_median$median

subject_highdisso <- subject_highdose[cadss_highdose > disso_median] 
subject_lowdisso <- subject_highdose[cadss_highdose <= disso_median]

test_data <- test_data %>%
  mutate(high_disso = case_when(Subjects %in% subject_highdisso ~ "high_dis", Subjects %in% subject_lowdisso ~ "low_dis")) %>%
  mutate(high_disso = factor(high_disso, levels = c("low_dis", "high_dis"))) %>%
  mutate(noncon_TvN_Right_antInsula_peak_nonconscious = as.numeric(noncon_TvN_Right_antInsula_peak_nonconscious)) %>%
  filter(Dosage == "0.5mg/kg") %>%
  na.omit() 

# summarize mean and sd

data_fortest_sta <- test_data %>%
  group_by(high_disso) %>%
  summarise(
    count = sum(!is.na(noncon_TvN_Right_antInsula_peak_nonconscious)),
    sd = sd(noncon_TvN_Right_antInsula_peak_nonconscious, na.rm = TRUE),
    se = sd / sqrt(count),
    avg = mean(noncon_TvN_Right_antInsula_peak_nonconscious, na.rm = TRUE))




ylim_max <- max(data_fortest_sta$avg) + 1.2 * max(data_fortest_sta$se)
ylim_min <- min(data_fortest_sta$avg) - 1.2 * max(data_fortest_sta$se)

colors_network_plot <- c("#A2DAB9", "#1E8E4C")
xlabel_text = c("low", "high")

myplot <- data_fortest_sta %>%
  ggplot(aes(x = high_disso, y = avg)) +
  geom_col(aes(fill = high_disso), alpha = 1, size = 0.25, position=position_dodge()) +
  geom_errorbar(aes(color = high_disso, ymin = avg-se, ymax = avg+se), width = 0, size = 0.25, position=position_dodge(.9)) + scale_colour_manual(values = colors_network_plot) + scale_fill_manual(values = colors_network_plot) + guides(color = guide_legend(override.aes= list(alpha = 1))) + scale_y_continuous(name="Size of effect", limits=c(0, 1.1), breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), expand = c(0, 0)) +  coord_cartesian(ylim = c(0.4, 0.8)) + theme_classic() #  c(ylim_min, ylim_max) + ggtitle("CADSS by Insula activation")
# if (ylim_min < 0) {
  myplot <- myplot + geom_hline(yintercept = 0, size = 0.1) 
# } 

xtitle_size = 6
title_size = 6
legend_title_size = 3
myplot <- add_theme(myplot, xtitle_size, title_size, legend_title_size)
myplot$labels$fill <- NULL
myplot <- myplot + scale_colour_manual(values = colors_network_plot)
leg <- get_legend(myplot)
plot_leg <- as_ggplot(leg)
myplot <- myplot + theme(legend.position = "off")

# TIFF
figure_width = 1.2
i_task <- "nonconscious"
i_con <- "ThreatvsNeutral"
ggsave(file=paste(Figuredir, "/TIFF/Boxplot/",i_task, "_",i_con, "_amnesia_insula_2col.TIFF", sep = ""), plot=myplot, width=figure_width, height=1.3, dpi = 1000)
# PDF
ggsave(file=paste(Figuredir, "/PDF/Boxplot/", i_task, "_",i_con,  "_amnesia_insula_2col.PDF", sep = ""), device = cairo_pdf, plot=myplot, width=figure_width, height=1.3, dpi = 300)
```

